# Generated by Django 3.2 on 2021-05-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.TextField(default='This was created beforehand'),
        ),
    ]
