# Generated by Django 3.2 on 2021-05-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.CharField(default='This was created beforehand', max_length=200),
        ),
    ]
